sudo: required
services:
    - docker

before_install:
    - docker build -t hiranthadocker/multi-docker -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true hiranthadocker/multi-docker npm run test -- --coverage

after_success: 
    - docker build -t hiranthadocker/multi-client ./client
    - docker build -t hiranthadocker/multi-nginx ./nginx 
    - docker build -t hiranthadocker/multi-server ./server
    - docker build -t hiranthadocker/multi-worker ./worker
    # Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Push to Docker Hub
    - docker push hiranthadocker/multi-client
    - docker push hiranthadocker/multi-nginx
    - docker push hiranthadocker/multi-server
    - docker push hiranthadocker/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-943870043357"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
