sudo: required
services:
    - docker

before_install:
    - docker build -t multi-docker -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true multi-docker npm run test -- --coverage

after_success: 
    - docker build -t hiranthdocker/multi-client ./client
    - docker build -t hiranthdocker/multi-nginx ./nginx 
    - docker build -t hiranthdocker/multi-server ./server
    - docker build -t hiranthdocker/multi-worker ./worker
    # Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Push to Docker Hub
    - docker push hiranthdocker/multi-client
    - docker push hiranthdocker/multi-nginx
    - docker push hiranthdocker/multi-server
    - docker push hiranthdocker/multi-worker


